apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: sgfv
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server:80
        access: proxy
        isDefault: true
      - name: Jaeger
        type: jaeger
        url: http://jaeger:16686
        access: proxy

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
  namespace: sgfv
data:
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: 'SGFV Dashboards'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
